(function(){
'use strict';
 var courtCanvas = document.getElementById('court');
 if (!courtCanvas.getContext || !courtCanvas.getContext('2d')) {
 document.getElementById('notice').textContent = 'This browser cannot draw the court. Open it on another device and mirror that screen to the TV.';
 return;
 }var C=window.Courtside,$=function(id){return document.getElementById(id);},settings=new C.Settings(),audio=new C.Audio(settings),camera=new C.Camera(),renderer=new C.Renderer($('court'),camera,settings),perf=new C.Performance();var network=null,lobby={players:[{},{}]},practice=/[?&]practice=1/.test(location.search),started=false,manual=false,showPair=false,joinURL='',lastUI='',lastFrame=performance.now(),accumulator=0,feedbackUntil=0,debug=/[?&]debug=1/.test(location.search),lastDiagnostics=0,lastState=0,botAt=[0,0],raf=0,localMotion=null,localTimer=0,localBusy=false;
var mode=settings.get('length','quick');var engine=new C.Engine(mode,onEvent),saved=C.storage.session('match');if(!practice&&saved&&Date.now()-saved.at<3600000){engine.restore(saved);if(engine.state==='MATCH_END')started=true;}
camera.mode=settings.get('camera','split');$('camera').value=camera.mode;$('length').value=mode;$('sound').checked=settings.get('sound',true);$('effects').checked=settings.get('effects',!(window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches));settings.set('effects',$('effects').checked);$('debug').hidden=!debug;
function persist(){if(!practice)C.storage.session('match',{score:engine.score,best:engine.best,at:Date.now()});}
function announce(text){if($('announce'))$('announce').textContent=text;}
function onEvent(e){if(e.type==='state'){lastUI='';return;}if(e.type!=='feedback')audio.play(e.type);renderer.effect(e);if(network&&e.player!==undefined)network.feedback(e.player,{text:e.text||e.type.toUpperCase(),type:e.type,shot:e.shot});if(e.type==='hit'||e.type==='milestone'){var label=e.type==='hit'?'P'+(e.player+1)+' · '+e.text+' / '+e.shot.toUpperCase():e.text;$('feedback').textContent=label;$('feedback').hidden=false;feedbackUntil=performance.now()+1000;}if(e.type==='point'||e.type==='game'||e.type==='match')announce((e.text||e.type)+' · '+engine.score.label(0)+' to '+engine.score.label(1));if(['point','game','match','fault'].indexOf(e.type)>=0){persist();lastUI='';}}
function bothReady(){return practice||lobby.players.every(function(p){return p.connected&&p.ready;});}
function reconcile(){if(!started||engine.state==='MATCH_END')return;if(!bothReady()){engine.pause(true);}else if(document.hidden||manual||showPair){engine.pause(false);}else if(['PAUSED','RECONNECTING','READY'].indexOf(engine.state)>=0)engine.resume();lastUI='';}
$('local-p1').onclick=function(){if(localBusy||!network)return;localBusy=true;if(!localMotion)localMotion=new C.Motion(function(power){if(started&&bothReady()){engine.input(0,{type:'swing',angle:localMotion.angle,spin:localMotion.spin,intensity:power,shot:'flat'});try{if(navigator.vibrate)navigator.vibrate(18);}catch(e){}}},function(a,s){engine.input(0,{type:'aim',angle:a,spin:s});});localMotion.enable().then(function(){if(!network.activateLocal()){localBusy=false;toast('P1 is already taken. Have that controller leave first.');return;}localMotion.calibrate();$('notice').textContent='Hold this phone still for 3 seconds to calibrate P1.';clearTimeout(localTimer);localTimer=setTimeout(function(){localBusy=false;if(localMotion.finish()&&network){network.localReady(true);$('local-p1').textContent='Recalibrate P1 grip';$('notice').textContent='P1 motion ready. Mirror this screen to your TV. The other phone joins P2.';}else $('notice').textContent='No sensor data. Retry calibration or connect two separate controllers.';},3000);},function(error){localBusy=false;toast(error.message);});};
function setupRoom(room){joinURL=C.url('controller.html')+'?room='+room;$('room-code').textContent=room;$('room-small').textContent='ROOM '+room;$('join-url').textContent=location.host+'/controller.html';$('join-url').href=joinURL;try{window.CourtQR.toCanvas($('qr'),joinURL,{width:220,margin:1,errorCorrectionLevel:'M'},function(error){if(error)$('notice').textContent='Enter the room code on your phone to join.';});}catch(e){$('qr').parentElement.hidden=true;}$('notice').textContent='Choose motion or touch on each phone, then tap Ready.';}
function connectNetwork(){if(network)return;network=new C.Network(true,null,{open:setupRoom,lobby:function(value){lobby=value;for(var i=0;i<2;i++)$('slot'+(i+1)).textContent=value.players[i].ready?'Ready to play':value.players[i].connected?'Connected · choose controls, then Ready':value.players[i].reserved?'Reconnecting…':'Waiting for phone';$('start').disabled=!bothReady();if(!started){if(bothReady())$('notice').textContent='Both players are ready. Start the match when you are.';else if(value.players.some(function(p){return p.connected&&!p.ready;}))$('notice').textContent='Connected. Choose motion or touch, then tap Ready on each phone.';}reconcile();},input:function(m){if(started&&!manual)engine.input(m.player,m.input);},offline:function(){$('notice').textContent='Court connection interrupted. Existing connections may recover automatically.';},error:function(message){$('notice').textContent=message;}});}
function loadPeer(){if(typeof window.Peer==='function'){connectNetwork();return;}if(!window.RTCPeerConnection){$('notice').textContent='This TV cannot connect phones. Use another device and mirror it to the TV, or try Practice.';if($('compat')){$('compat').hidden=false;$('compat').textContent='COURT MODE LIMITED · This browser cannot connect phones directly. Open the court on another device and mirror it.';}return;}var script=document.createElement('script');script.src='https://unpkg.com/peerjs@1.5.5/dist/peerjs.min.js';script.onload=connectNetwork;script.onerror=function(){$('notice').textContent='Multiplayer could not load. Reload this page to retry, or try Practice.';};document.head.appendChild(script);}
function start(){audio.unlock();if(!bothReady())return;started=true;showPair=false;manual=false;if(engine.score.winner<0)engine.resume();lastUI='';}
$('start').onclick=start;$('practice').onclick=function(){clearTimeout(localTimer);localBusy=false;if(localMotion){localMotion.destroy();localMotion=null;}if(network){network.destroy();network=null;}practice=true;engine=new C.Engine('rally',onEvent);started=true;showPair=false;manual=false;engine.resume();$('room-small').textContent='PRACTICE';$('footer-tip').textContent='Space or tap the court to swing · ← → aim · P2 returns automatically';};
$('pause').onclick=function(){if(!started)return;manual=!manual;reconcile();};$('resume').onclick=function(){manual=false;showPair=false;reconcile();};$('pair-again').onclick=function(){showPair=true;lastUI='';};
$('rematch').onclick=function(){reset(false);};$('practice-serve').onclick=practiceSwing;
function reset(confirmFirst){if(confirmFirst&&started&&!window.confirm('Start a new match and clear the score?'))return;engine=new C.Engine(practice?'rally':settings.get('length','quick'),onEvent);persist();manual=false;showPair=false;started=bothReady();if(started)engine.resume();$('settings').hidden=true;lastUI='';}
$('new-match').onclick=function(){reset(true);};$('settings-open').onclick=function(){manual=started;reconcile();$('settings').hidden=false;$('camera').focus();};$('settings-close').onclick=function(){$('settings').hidden=true;$('settings-open').focus();};$('camera').onchange=function(){camera.mode=this.value;settings.set('camera',this.value);lastUI='';};$('length').onchange=function(){settings.set('length',this.value);};$('sound').onchange=function(){settings.set('sound',this.checked);if(this.checked&&!audio.unlock())$('settings-status').textContent='Audio is unavailable in this browser.';};$('effects').onchange=function(){settings.set('effects',this.checked);};
$('fullscreen').onclick=function(){var d=document.documentElement,fn=d.requestFullscreen||d.webkitRequestFullscreen;try{if(document.fullscreenElement){var result=document.exitFullscreen();if(result&&result.catch)result.catch(function(){});}else if(fn){var p=fn.call(d);if(p&&p.catch)p.catch(function(){toast('Use the TV browser’s full-screen option.');});}else toast('Use the TV browser’s full-screen option.');}catch(e){toast('Full screen is unavailable in this browser.');}};
function toast(text){$('feedback').textContent=text;$('feedback').hidden=false;feedbackUntil=performance.now()+4000;}
$('new-room').onclick=function(){
  clearTimeout(localTimer);localBusy=false;
  if(localMotion){localMotion.destroy();localMotion=null;}
  if(network)network.destroy();network=null;C.storage.session('room',null);lobby={players:[{},{}]};$('start').disabled=true;showPair=true;reconcile();$('settings').hidden=true;if(typeof window.Peer==='function')connectNetwork();else loadPeer();
};
$('copy').onclick=function(){if(!joinURL)return;if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(joinURL).then(function(){$('notice').textContent='Join link copied.';},function(){$('notice').textContent=joinURL;});else $('notice').textContent=joinURL;};
function practiceSwing(){if(!practice||!started)return;audio.unlock();engine.input(0,{type:'swing',angle:engine.players[0].aim,intensity:.65,shot:'flat'});}
$('court').addEventListener('pointerdown',practiceSwing);document.addEventListener('keydown',function(e){if(!$('settings').hidden){if(e.key==='Escape')$('settings-close').click();if(e.key==='Tab'){var nodes=$('settings').querySelectorAll('button,select,input,summary,a'),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}if(e.target.tagName==='SELECT')return;if(!started&&bothReady()&&(e.key==='Enter'||e.key===' ')&&$('pair-overlay')&&!$('pair-overlay').hidden){e.preventDefault();start();return;}if(practice&&(e.code==='Space'||e.key===' ')){e.preventDefault();practiceSwing();}if(practice&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){e.preventDefault();engine.players[0].aim=C.clamp(engine.players[0].aim+(e.key==='ArrowLeft'?-.2:.2),-1,1);}if(e.key==='Escape')$('pause').click();});
document.addEventListener('visibilitychange',function(){accumulator=0;lastFrame=performance.now();if(network&&localMotion)network.localReady(!document.hidden&&localMotion.calibrated);reconcile();persist();});window.addEventListener('resize',function(){renderer.resize();});
function updateUI(){var s=engine.score,key=JSON.stringify([engine.state,s.points,s.games,s.sets,s.server,s.winner,Math.ceil(engine.count),engine.rally,engine.best,manual,showPair,started,bothReady(),camera.mode,engine.caption]);if(key===lastUI)return;lastUI=key;for(var i=0;i<2;i++){$('score'+(i+1)).textContent=s.label(i);$('games'+(i+1)).textContent=s.games[i]+' GAMES · '+s.sets[i]+' SETS';$('serve'+(i+1)).textContent=s.server===i?'●':'';}$('rally').textContent='RALLY '+engine.rally+' · BEST '+engine.best;var names={quick:'QUICK MATCH',three:'FIRST TO 3',set:'ONE SET',best3:'BEST OF 3 SETS',rally:'ARCADE RALLY'};$('match-label').textContent=s.tie?'TIEBREAK':names[s.mode];$('camera-label').textContent=camera.mode==='split'?'SPLIT SCREEN / TWO BASELINES':camera.mode.toUpperCase();$('pause').textContent=manual?'Resume':'Pause';$('pair-overlay').hidden=started&&!showPair;$('moment-overlay').hidden=!started||showPair||engine.state==='RALLY';$('resume').hidden=true;$('practice-serve').hidden=!(practice&&engine.state==='SERVING'&&s.server===0);$('rematch').hidden=true;$('pair-again').hidden=true;$('moment-title').className='';var title='',sub='',kicker='CENTRE COURT';if(engine.state==='COUNTDOWN'){title=String(Math.ceil(engine.count));kicker='GET READY';sub='Both players · Eyes on the court';$('moment-title').className='countdown';}else if(engine.state==='SERVING'){title='YOUR SERVE, P'+(s.server+1);sub=engine.faults?'Second serve. Aim across the net into the opposite service box.':'Swing to serve. Aim into the opposite service box.';kicker=practice?'SPACE OR TAP THE COURT':'LOOK UP. SWING WHEN READY.';}else if(engine.state==='RECONNECTING'){title='MATCH PAUSED';sub=lobby.players.map(function(p,i){return !p.connected?'P'+(i+1)+' reconnecting…':!p.ready?'P'+(i+1)+' needs to tap Ready':'';}).filter(Boolean).join(' · ');kicker='YOUR SCORE IS SAFE';$('pair-again').hidden=false;}else if(engine.state==='PAUSED'){title='TAKE A BREATHER';sub='Resume when both players are ready.';$('resume').hidden=!bothReady();}else if(engine.state==='MATCH_END'){title='PLAYER '+(s.winner+1)+' WINS';sub='Best rally · '+engine.best+' shots';kicker='GAME. SET. MATCH.';$('rematch').hidden=false;}else if(engine.state==='POINT_END'||engine.state==='GAME_END'){title=engine.state==='GAME_END'?'GAME · P'+(engine.pointWinner+1):engine.caption;sub='Point to Player '+(engine.pointWinner+1);kicker=s.points[0]>=3&&s.points[1]>=3?(s.points[0]===s.points[1]?'DEUCE':'ADVANTAGE'):'WELL PLAYED';}$('moment-title').textContent=title;$('moment-sub').textContent=sub;$('moment-kicker').textContent=kicker;}
window.addEventListener('orientationchange',function(){if(localMotion&&localMotion.calibrated){localMotion.calibrated=false;network.localReady(false);showPair=true;reconcile();$('notice').textContent='Phone rotated. Recalibrate your P1 grip.';}});
function frame(now){if(localMotion&&localMotion.calibrated&&now-localMotion.lastSample>5000){localMotion.calibrated=false;if(network)network.localReady(false);showPair=true;reconcile();$('notice').textContent='P1 sensor data stopped. Recalibrate your grip.';}var elapsed=Math.max(0,(now-lastFrame)/1000);lastFrame=now;var dt=Math.min(elapsed,.1);if(elapsed>.35&&started&&['RALLY','SERVING'].indexOf(engine.state)>=0){manual=true;reconcile();toast('Playback paused after an interruption. Resume when ready.');}var ticks=0;accumulator+=dt;while(accumulator>=C.config.step&&ticks<C.config.maxSteps){if(practice&&engine.state==='SERVING'&&engine.score.server===1)engine.input(1,{type:'swing',angle:0,intensity:.6,shot:'flat'});if(practice&&engine.inZone(1)&&engine.time-botAt[1]>.4){botAt[1]=engine.time;engine.input(1,{type:'swing',angle:Math.sin(engine.rally)*.45,intensity:.6,shot:'topspin'});}engine.tick(C.config.step);accumulator-=C.config.step;ticks++;}if(accumulator>=C.config.step){perf.dropped++;accumulator=0;}renderer.draw(engine,accumulator/C.config.step,dt);perf.frame(dt,ticks);updateUI();if(feedbackUntil&&now>feedbackUntil){$('feedback').hidden=true;feedbackUntil=0;}if(network&&now-lastState>500){lastState=now;network.state({phase:engine.state,server:engine.score.server,points:[engine.score.label(0),engine.score.label(1)],rally:engine.rally});}if(debug&&now-lastDiagnostics>500){lastDiagnostics=now;$('debug').textContent='FPS '+perf.fps+' | SIM '+perf.hz+' Hz\nSTATE '+engine.state+'\nPEER '+(network?network.peerState:'PRACTICE')+' | PACKETS/S '+(network?network.packetRate:0)+'\nCANVAS '+renderer.w+'×'+renderer.h+' | DROPPED '+perf.dropped;}raf=requestAnimationFrame(frame);}
if(practice){$('practice').click();}else loadPeer();raf=requestAnimationFrame(frame);window.addEventListener('pagehide',function(){persist();if(network)network.destroy();if(localMotion)localMotion.destroy();clearTimeout(localTimer);cancelAnimationFrame(raf);});window.addEventListener('pageshow',function(e){if(e.persisted)location.reload();});
})();
