(function(root){
'use strict';var C=root.Courtside;
C.Motion=function(onSwing,onAim){this.onSwing=onSwing;this.onAim=onAim;this.enabled=false;this.calibrating=false;this.calibrated=false;this.gamma=0;this.beta=0;this.neutral=[0,0];this.noise=0;this.force=0;this.axis=0;this.energy=[0,0,0];this.gravity=null;this.armed=true;this.lastSwing=-Infinity;this.lastAim=0;this.lastSample=0;this.angle=0;this.spin=0;this.threshold=18;this.samples=0;this.sum=0;var self=this;this.motionHandler=function(e){self.motion(e);};this.orientationHandler=function(e){self.orientation(e);};};
C.Motion.prototype.enable=function(){var self=this;if(!root.isSecureContext||!root.DeviceMotionEvent)return Promise.reject(new Error('Motion is unavailable here. Choose touch controls.'));var m=typeof root.DeviceMotionEvent.requestPermission==='function'?root.DeviceMotionEvent.requestPermission():Promise.resolve('granted');var o=root.DeviceOrientationEvent&&typeof root.DeviceOrientationEvent.requestPermission==='function'?root.DeviceOrientationEvent.requestPermission():Promise.resolve('granted');return Promise.all([m,o.catch(function(){return 'denied';})]).then(function(results){if(results[0]!=='granted')throw new Error('Motion access was denied. Touch controls are ready to use.');if(!self.enabled){root.addEventListener('devicemotion',self.motionHandler);root.addEventListener('deviceorientation',self.orientationHandler);self.enabled=true;}return results[1]==='granted';});};
C.Motion.prototype.calibrate=function(){this.calibrating=true;this.calibrated=false;this.samples=0;this.sum=0;this.sumG=0;this.sumB=0;this.started=performance.now();this.gravity=null;this.energy=[0,0,0];this.armed=false;};
C.Motion.prototype.finish=function(){this.calibrating=false;if(this.samples<15)return false;this.neutral=[this.sumG/this.samples,this.sumB/this.samples];this.noise=this.sum/this.samples;this.calibrated=true;this.force=0;this.armed=false;this.lastSwing=performance.now();return true;};
C.Motion.prototype.orientation=function(e){if(C.finite(e.gamma))this.gamma=e.gamma;if(C.finite(e.beta))this.beta=e.beta;if(!this.calibrated||document.hidden)return;var rotation=root.screen&&root.screen.orientation?root.screen.orientation.angle:root.orientation||0,side=rotation===90?this.beta-this.neutral[1]:rotation===270||rotation===-90?-(this.beta-this.neutral[1]):this.gamma-this.neutral[0];var desired=C.clamp(side/35,-1,1);this.angle+=.22*(desired-this.angle);if(Math.abs(this.angle)<.06)this.angle=0;this.spin=C.clamp((this.beta-this.neutral[1])/40,-1,1);var now=performance.now();if(now-this.lastAim>50){this.lastAim=now;this.onAim(this.angle,this.spin);}};
C.Motion.prototype.motion=function(e){if(document.hidden)return;var a=e.acceleration,v;if(a&&C.finite(a.x)&&C.finite(a.y)&&C.finite(a.z))v=[a.x,a.y,a.z];else{a=e.accelerationIncludingGravity;if(!a||!C.finite(a.x)||!C.finite(a.y)||!C.finite(a.z))return;var raw=[a.x,a.y,a.z];if(!this.gravity){this.gravity=raw;return;}v=[];for(var i=0;i<3;i++){v[i]=raw[i]-this.gravity[i];this.gravity[i]+=.08*(raw[i]-this.gravity[i]);}}var now=performance.now();this.lastSample=now;var magnitude=Math.sqrt(v[0]*v[0]+v[1]*v[1]+v[2]*v[2]);if(this.calibrating){if(now-this.started<2000){this.samples++;this.sum+=magnitude;this.sumG+=this.gamma;this.sumB+=this.beta;}else{for(var axisIndex=0;axisIndex<3;axisIndex++)this.energy[axisIndex]+=v[axisIndex]*v[axisIndex];this.axis=this.energy.indexOf(Math.max.apply(Math,this.energy));}return;}if(!this.calibrated)return;for(var n=0;n<3;n++)this.energy[n]=.9*this.energy[n]+.1*v[n]*v[n];this.axis=this.energy.indexOf(Math.max.apply(Math,this.energy));var alpha=magnitude>this.force?.7:.22;this.force+=alpha*(magnitude-this.force);var threshold=Math.max(this.threshold,this.noise*3+7);if(this.force<threshold*.45)this.armed=true;if(this.armed&&this.force>threshold&&now-this.lastSwing>320){this.armed=false;this.lastSwing=now;this.onSwing(C.clamp(.3+(this.force-threshold)/32,.2,1));}};
C.Motion.prototype.destroy=function(){root.removeEventListener('devicemotion',this.motionHandler);root.removeEventListener('deviceorientation',this.orientationHandler);this.enabled=false;};
})(typeof window!=='undefined'?window:globalThis);
